---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://stensonb.github.io/chloesrecipes"
title: "Hugo Blog Template for GitHub Pages"
...
